apiVersion: v1
kind: Service
metadata:
  name: alarm-service
spec:
  selector:
    app: alarm-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: alarm-db-service
spec:
  selector:
    app: alarm-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: parsermanager-service
spec:
  selector:
    app: parsermanager
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: builder-service
spec:
  selector:
    app: builder
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
---
apiVersion: v1
kind: Service
metadata:
  name: parser-get-host-service
spec:
  selector:
    app: builder
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo_db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: log-auth-db-service
spec:
  selector:
    app: log-auth-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: log-auth-service
spec:
  selector:
    app: log-auth
  ports:
    - protocol: TCP
      port: 7900
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: log-store-esdb-service
spec:
  selector:
    app: log-store-esdb
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: log-store-service
spec:
  selector:
    app: log-store
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: interface-service
spec:
  selector:
    app: website-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-service
spec:
  type: NodePort
  selector:
    app: reverse-proxy
  ports:
    - protocol: TCP
      name: http
      port: 8092
      targetPort: 80
      nodePort: 30077
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443

