apiVersion: v1
kind: Service
metadata:
  name: log-auth-db-service
spec:
  selector:
    app: log-auth-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-auth-db-deployment
  labels:
    app: log-auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-auth-db
  template:
    metadata:
      labels:
        app: log-auth-db
    spec:
      containers:
      - name: log-auth-db
        image: logops/subscriptiondb:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
