apiVersion: v1
kind: Service
metadata:
  name: interface-service
spec:
  selector:
    app: website-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: website-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-app
  template:
    metadata:
      labels:
        app: website-app
    spec:
      containers:
      - name: apache
        image: logops/logops_apache:develop
        imagePullPolicy: Always
        env:
        - name: php_ADDR
          value: localhost
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
      - name: php
        image: logops/logops_php:develop
        imagePullPolicy: Always
        env:
        - name: GLOBAL_URL
          value: http://a327e724323e011ea8592062e1a075a4-552548340.eu-central-1.elb.amazonaws.com
        - name: LOGSTORE_URL
          value: http://a327e724323e011ea8592062e1a075a4-552548340.eu-central-1.elb.amazonaws.com
        - name: ALARMSERVICE_URL
          value: http://a327e724323e011ea8592062e1a075a4-552548340.eu-central-1.elb.amazonaws.com
        - name: JOLIECLOUD_URL
          value: http://a327e724323e011ea8592062e1a075a4-552548340.eu-central-1.elb.amazonaws.com
        - name: AUTHSERVICE_URL
          value: http://a327e724323e011ea8592062e1a075a4-552548340.eu-central-1.elb.amazonaws.com/auth
        - name: MYSQL_ADDR
          value: 127.0.0.1
      - name: mysql
        image: logops/logops_mysql:develop
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
